linkPrefix = ""
name = "security-token"
version = "1.0.0"
description = ""
buildTime = 2018-12-19T08:18:59.850Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = ""
license = "ISC"

[interaction]